import type { Project } from './types';
import { SOC2_MOCKUP_TASKS } from './components/soc2-mockup-data';

// Mock Projects Data
export const mockProjects: Project[] = [
  {
    id: 'project-1',
    name: 'HIPAA Compliance',
    description: 'Healthcare compliance project ensuring all systems meet HIPAA requirements for patient data protection and privacy.',
    status: 'active',
    complianceScore: 78,
    dataSources: [
      { type: 'codebase', id: 'cb-1', name: 'patient-portal-api' },
      { type: 'codebase', id: 'cb-2', name: 'medical-records-db' },
      { type: 'document', id: 'doc-1', name: 'HIPAA Privacy Rule.pdf' },
      { type: 'document', id: 'doc-2', name: 'HIPAA Security Rule.pdf' },
      { type: 'user', id: 'user-1', name: 'Sarah Johnson' },
      { type: 'user', id: 'user-2', name: 'Michael Chen' },
    ],
    tasks: [
      {
        id: 'task-1',
        title: 'Implement encryption at rest',
        description: 'Add encryption for all patient data stored in the database',
        taskType: 'security-issue',
        author: {
          name: 'Security Auditor',
          role: 'Security Team',
          type: 'human',
        },
        status: 'in-progress',
        priority: 'critical',
        assignedTo: 'Michael Chen',
        dueDate: '2025-10-15',
        createdAt: '2025-09-20T10:00:00Z',
      },
      {
        id: 'task-2',
        title: 'Update access control policies',
        description: 'Review and update role-based access controls for PHI',
        taskType: 'documentation-issue',
        author: {
          name: 'Compliance Officer',
          role: 'Compliance Team',
          type: 'human',
        },
        status: 'todo',
        priority: 'high',
        assignedTo: 'Sarah Johnson',
        dueDate: '2025-10-20',
        createdAt: '2025-09-22T14:30:00Z',
      },
      {
        id: 'task-3',
        title: 'Audit logging implementation',
        description: 'Implement comprehensive audit logging for all PHI access',
        taskType: 'missing-data',
        author: {
          name: 'HIPAA Auditor',
          role: 'HIPAA General Auditor',
          type: 'ai',
        },
        status: 'completed',
        priority: 'high',
        createdAt: '2025-09-15T09:00:00Z',
      },
      ...SOC2_MOCKUP_TASKS,
    ],
    agentTasks: [
      {
        id: 'agent-task-1',
        title: 'HIPAA Compliance Scan',
        description: 'Automated scan of patient-portal-api for HIPAA compliance violations',
        status: 'completed',
        type: 'scan',
        progress: 100,
        trigger: 'scheduled',
        schedule: '0 0 * * 0', // Weekly on Sunday
        lastRunAt: '2025-09-25T08:15:00Z',
        startedAt: '2025-09-25T08:00:00Z',
        completedAt: '2025-09-25T08:15:00Z',
        result: 'Scan completed successfully. Found 12 issues requiring attention.',
        findings: {
          critical: 2,
          high: 4,
          medium: 5,
          low: 1,
        },
        nodes: [
          { id: 'start', name: 'Start', type: 'start', status: 'completed', position: { x: 250, y: 0 } },
          { id: 'fetch-code', name: 'Fetch Codebase', type: 'action', status: 'completed', position: { x: 250, y: 100 } },
          { id: 'analyze-phi', name: 'Analyze PHI Handling', type: 'analysis', status: 'completed', position: { x: 250, y: 200 } },
          { id: 'check-critical', name: 'Critical Issues?', type: 'decision', status: 'completed', condition: 'If critical issues found', position: { x: 250, y: 300 } },
          { id: 'immediate-fix', name: 'Immediate Fix Required', type: 'action', status: 'completed', position: { x: 100, y: 400 } },
          { id: 'check-encryption', name: 'Check Encryption', type: 'analysis', status: 'completed', position: { x: 400, y: 400 } },
          { id: 'check-access', name: 'Check Access Controls', type: 'analysis', status: 'completed', position: { x: 250, y: 500 } },
          { id: 'audit-logs', name: 'Audit Log Review', type: 'analysis', status: 'completed', optional: true, position: { x: 450, y: 500 } },
          { id: 'generate-report', name: 'Generate Report', type: 'action', status: 'completed', position: { x: 250, y: 600 } },
          { id: 'end', name: 'End', type: 'end', status: 'completed', position: { x: 250, y: 700 } },
        ],
        edges: [
          { id: 'e1', source: 'start', target: 'fetch-code' },
          { id: 'e2', source: 'fetch-code', target: 'analyze-phi' },
          { id: 'e3', source: 'analyze-phi', target: 'check-critical' },
          { id: 'e4', source: 'check-critical', target: 'immediate-fix', label: 'Yes', condition: 'critical_issues_found' },
          { id: 'e5', source: 'check-critical', target: 'check-encryption', label: 'No', condition: 'no_critical_issues' },
          { id: 'e6', source: 'immediate-fix', target: 'check-access' },
          { id: 'e7', source: 'check-encryption', target: 'check-access' },
          { id: 'e8', source: 'check-access', target: 'audit-logs', type: 'conditional', label: 'If enabled' },
          { id: 'e9', source: 'check-access', target: 'generate-report' },
          { id: 'e10', source: 'audit-logs', target: 'generate-report' },
          { id: 'e11', source: 'generate-report', target: 'end' },
        ],
        runHistory: [
          {
            id: 'run-1',
            startedAt: '2025-09-25T08:00:00Z',
            completedAt: '2025-09-25T08:15:00Z',
            status: 'completed',
            duration: 900,
            findings: { critical: 2, high: 4, medium: 5, low: 1 },
          },
          {
            id: 'run-2',
            startedAt: '2025-09-18T08:00:00Z',
            completedAt: '2025-09-18T08:12:00Z',
            status: 'completed',
            duration: 720,
            findings: { critical: 3, high: 5, medium: 4, low: 2 },
          },
          {
            id: 'run-3',
            startedAt: '2025-09-11T08:00:00Z',
            completedAt: '2025-09-11T08:14:00Z',
            status: 'completed',
            duration: 840,
            findings: { critical: 2, high: 6, medium: 3, low: 1 },
          },
        ],
      },
      {
        id: 'agent-task-2',
        title: 'PHI Data Flow Analysis',
        description: 'Analyzing data flow patterns to identify potential PHI exposure risks',
        status: 'running',
        type: 'analysis',
        progress: 65,
        trigger: 'manual',
        lastRunAt: '2025-09-28T14:20:00Z',
        startedAt: '2025-10-01T10:30:00Z',
        nodes: [
          { id: 'start', name: 'Start', type: 'start', status: 'completed', position: { x: 250, y: 0 } },
          { id: 'map-data', name: 'Map Data Sources', type: 'analysis', status: 'completed', position: { x: 250, y: 100 } },
          { id: 'parallel-trace', name: 'Parallel Analysis', type: 'parallel', status: 'running', position: { x: 250, y: 200 } },
          { id: 'trace-flows', name: 'Trace Data Flows', type: 'analysis', status: 'running', position: { x: 150, y: 300 } },
          { id: 'check-permissions', name: 'Check Permissions', type: 'analysis', status: 'running', position: { x: 350, y: 300 } },
          { id: 'identify-risks', name: 'Identify Risks', type: 'analysis', status: 'pending', position: { x: 250, y: 400 } },
          { id: 'risk-level', name: 'Risk Level?', type: 'decision', status: 'pending', condition: 'Assess risk severity', position: { x: 250, y: 500 } },
          { id: 'high-risk-action', name: 'Immediate Action', type: 'action', status: 'pending', position: { x: 100, y: 600 } },
          { id: 'generate-diagram', name: 'Generate Diagram', type: 'action', status: 'pending', position: { x: 400, y: 600 } },
          { id: 'compliance-check', name: 'Compliance Check', type: 'analysis', status: 'pending', optional: true, position: { x: 250, y: 700 } },
          { id: 'end', name: 'End', type: 'end', status: 'pending', position: { x: 250, y: 800 } },
        ],
        edges: [
          { id: 'e1', source: 'start', target: 'map-data' },
          { id: 'e2', source: 'map-data', target: 'parallel-trace' },
          { id: 'e3', source: 'parallel-trace', target: 'trace-flows', type: 'parallel' },
          { id: 'e4', source: 'parallel-trace', target: 'check-permissions', type: 'parallel' },
          { id: 'e5', source: 'trace-flows', target: 'identify-risks' },
          { id: 'e6', source: 'check-permissions', target: 'identify-risks' },
          { id: 'e7', source: 'identify-risks', target: 'risk-level' },
          { id: 'e8', source: 'risk-level', target: 'high-risk-action', label: 'High Risk', condition: 'high_risk' },
          { id: 'e9', source: 'risk-level', target: 'generate-diagram', label: 'Low/Medium', condition: 'low_medium_risk' },
          { id: 'e10', source: 'high-risk-action', target: 'compliance-check' },
          { id: 'e11', source: 'generate-diagram', target: 'compliance-check' },
          { id: 'e12', source: 'compliance-check', target: 'end' },
          { id: 'e13', source: 'generate-diagram', target: 'end', type: 'conditional', label: 'Skip compliance' },
        ],
        runHistory: [
          {
            id: 'run-1',
            startedAt: '2025-09-28T14:20:00Z',
            completedAt: '2025-09-28T15:05:00Z',
            status: 'completed',
            duration: 2700,
            findings: { critical: 1, high: 2, medium: 4, low: 3 },
          },
        ],
      },
      {
        id: 'agent-task-3',
        title: 'Generate Compliance Report',
        description: 'Generate comprehensive HIPAA compliance report for Q3 2025',
        status: 'pending',
        type: 'report',
        progress: 0,
        trigger: 'scheduled',
        schedule: '0 0 1 * *', // Monthly on the 1st
        nodes: [
          { id: 'start', name: 'Start', type: 'start', status: 'pending', position: { x: 250, y: 0 } },
          { id: 'collect-data', name: 'Collect Data', type: 'action', status: 'pending', position: { x: 250, y: 100 } },
          { id: 'data-quality', name: 'Data Quality OK?', type: 'decision', status: 'pending', condition: 'Check data completeness', position: { x: 250, y: 200 } },
          { id: 'retry-collection', name: 'Retry Collection', type: 'action', status: 'pending', position: { x: 100, y: 300 } },
          { id: 'analyze-compliance', name: 'Analyze Compliance', type: 'analysis', status: 'pending', position: { x: 400, y: 300 } },
          { id: 'executive-summary', name: 'Executive Summary', type: 'action', status: 'pending', optional: true, position: { x: 150, y: 400 } },
          { id: 'detailed-analysis', name: 'Detailed Analysis', type: 'action', status: 'pending', position: { x: 350, y: 400 } },
          { id: 'generate-pdf', name: 'Generate PDF', type: 'action', status: 'pending', position: { x: 250, y: 500 } },
          { id: 'email-stakeholders', name: 'Email Stakeholders', type: 'action', status: 'pending', optional: true, position: { x: 450, y: 500 } },
          { id: 'end', name: 'End', type: 'end', status: 'pending', position: { x: 250, y: 600 } },
        ],
        edges: [
          { id: 'e1', source: 'start', target: 'collect-data' },
          { id: 'e2', source: 'collect-data', target: 'data-quality' },
          { id: 'e3', source: 'data-quality', target: 'retry-collection', label: 'No', condition: 'data_incomplete' },
          { id: 'e4', source: 'data-quality', target: 'analyze-compliance', label: 'Yes', condition: 'data_complete' },
          { id: 'e5', source: 'retry-collection', target: 'data-quality' },
          { id: 'e6', source: 'analyze-compliance', target: 'executive-summary', type: 'conditional', label: 'If requested' },
          { id: 'e7', source: 'analyze-compliance', target: 'detailed-analysis' },
          { id: 'e8', source: 'executive-summary', target: 'generate-pdf' },
          { id: 'e9', source: 'detailed-analysis', target: 'generate-pdf' },
          { id: 'e10', source: 'generate-pdf', target: 'email-stakeholders', type: 'conditional', label: 'If enabled' },
          { id: 'e11', source: 'generate-pdf', target: 'end' },
          { id: 'e12', source: 'email-stakeholders', target: 'end' },
        ],
        runHistory: [],
      },
    ],
    documentation: [
      {
        id: 'doc-page-1',
        title: 'Overview',
        content: '# HIPAA Compliance Overview\n\nThis project ensures our healthcare systems comply with HIPAA regulations.\n\n## Goals\n- Protect patient health information (PHI)\n- Implement required security measures\n- Maintain compliance documentation',
        order: 1,
        createdAt: '2025-09-01T10:00:00Z',
        updatedAt: '2025-09-01T10:00:00Z',
      },
      {
        id: 'doc-page-2',
        title: 'Technical Requirements',
        content: '# Technical Requirements\n\n## Encryption\n- All PHI must be encrypted at rest\n- TLS 1.2+ for data in transit\n\n## Access Control\n- Role-based access control (RBAC)\n- Multi-factor authentication\n- Session timeout after 15 minutes',
        order: 2,
        children: [
          {
            id: 'doc-page-2-1',
            title: 'Database Security',
            content: '# Database Security\n\n## Requirements\n- Encrypted connections only\n- Audit logging enabled\n- Regular backups with encryption',
            order: 1,
            createdAt: '2025-09-02T11:00:00Z',
            updatedAt: '2025-09-02T11:00:00Z',
          },
          {
            id: 'doc-page-2-2',
            title: 'API Security',
            content: '# API Security\n\n## Authentication\n- OAuth 2.0 with JWT tokens\n- API key rotation every 90 days\n\n## Rate Limiting\n- 1000 requests per hour per user',
            order: 2,
            createdAt: '2025-09-02T12:00:00Z',
            updatedAt: '2025-09-02T12:00:00Z',
          },
        ],
        createdAt: '2025-09-01T11:00:00Z',
        updatedAt: '2025-09-01T11:00:00Z',
      },
      {
        id: 'doc-page-3',
        title: 'Compliance Checklist',
        content: '# Compliance Checklist\n\n## Privacy Rule\n- [ ] Patient consent forms\n- [x] Privacy notice posted\n- [x] Minimum necessary standard\n\n## Security Rule\n- [x] Risk assessment completed\n- [ ] Security training for all staff\n- [x] Incident response plan',
        order: 3,
        createdAt: '2025-09-01T12:00:00Z',
        updatedAt: '2025-09-25T14:00:00Z',
      },
    ],
    createdAt: '2025-09-01T09:00:00Z',
    updatedAt: '2025-09-25T14:00:00Z',
  },
  {
    id: 'project-2',
    name: 'GDPR Data Protection',
    description: 'Ensuring compliance with EU General Data Protection Regulation for customer data handling and privacy.',
    status: 'active',
    complianceScore: 92,
    dataSources: [
      { type: 'codebase', id: 'cb-3', name: 'customer-api' },
      { type: 'codebase', id: 'cb-4', name: 'analytics-service' },
      { type: 'document', id: 'doc-3', name: 'GDPR Guidelines.pdf' },
      { type: 'user', id: 'user-3', name: 'Emily Rodriguez' },
    ],
    tasks: [
      {
        id: 'task-4',
        title: 'Data retention policy update',
        description: 'Update data retention policies to comply with GDPR Article 5',
        taskType: 'documentation-issue',
        author: {
          name: 'GDPR Compliance Officer',
          role: 'Compliance Team',
          type: 'human',
        },
        status: 'completed',
        priority: 'high',
        assignedTo: 'Emily Rodriguez',
        createdAt: '2025-09-10T10:00:00Z',
      },
      {
        id: 'task-5',
        title: 'Cookie consent banner',
        description: 'Implement compliant cookie consent mechanism',
        taskType: 'documentation-issue',
        author: {
          name: 'Privacy Officer',
          role: 'Privacy Team',
          type: 'human',
        },
        status: 'completed',
        priority: 'medium',
        createdAt: '2025-09-12T11:00:00Z',
      },
    ],
    agentTasks: [
      {
        id: 'agent-task-4',
        title: 'GDPR Data Mapping',
        description: 'Automated mapping of personal data across all systems',
        status: 'completed',
        type: 'analysis',
        progress: 100,
        startedAt: '2025-09-15T09:00:00Z',
        completedAt: '2025-09-15T10:30:00Z',
        result: 'Successfully mapped 47 data processing activities.',
        findings: {
          critical: 0,
          high: 1,
          medium: 3,
          low: 2,
        },
      },
      {
        id: 'agent-task-5',
        title: 'Right to Erasure Audit',
        description: 'Verify implementation of data deletion mechanisms',
        status: 'completed',
        type: 'scan',
        progress: 100,
        startedAt: '2025-09-18T14:00:00Z',
        completedAt: '2025-09-18T14:45:00Z',
        result: 'All systems properly implement data deletion.',
        findings: {
          critical: 0,
          high: 0,
          medium: 1,
          low: 0,
        },
      },
    ],
    documentation: [
      {
        id: 'doc-page-4',
        title: 'GDPR Overview',
        content: '# GDPR Compliance\n\nEnsuring our data processing activities comply with GDPR.\n\n## Key Principles\n- Lawfulness, fairness, transparency\n- Purpose limitation\n- Data minimization\n- Accuracy\n- Storage limitation\n- Integrity and confidentiality',
        order: 1,
        createdAt: '2025-09-10T09:00:00Z',
        updatedAt: '2025-09-10T09:00:00Z',
      },
    ],
    createdAt: '2025-09-10T08:00:00Z',
    updatedAt: '2025-09-20T16:00:00Z',
  },
  {
    id: 'project-3',
    name: 'SOX Financial Controls',
    description: 'Sarbanes-Oxley compliance for financial reporting systems and internal controls.',
    status: 'on-hold',
    complianceScore: 65,
    dataSources: [
      { type: 'codebase', id: 'cb-5', name: 'financial-reporting' },
      { type: 'document', id: 'doc-4', name: 'SOX Requirements.pdf' },
      { type: 'user', id: 'user-4', name: 'David Kim' },
    ],
    tasks: [
      {
        id: 'task-6',
        title: 'Implement change management controls',
        description: 'Set up approval workflows for production changes',
        taskType: 'security-issue',
        author: {
          name: 'SOX Auditor',
          role: 'Finance Compliance Team',
          type: 'human',
        },
        status: 'todo',
        priority: 'high',
        dueDate: '2025-11-01',
        createdAt: '2025-09-18T10:00:00Z',
      },
    ],
    agentTasks: [
      {
        id: 'agent-task-6',
        title: 'SOX Control Assessment',
        description: 'Assess IT general controls for SOX compliance',
        status: 'failed',
        type: 'scan',
        progress: 45,
        startedAt: '2025-09-20T11:00:00Z',
        completedAt: '2025-09-20T11:30:00Z',
        result: 'Scan failed: Unable to access financial-reporting-api. Please check credentials.',
      },
      {
        id: 'agent-task-7',
        title: 'Access Control Review',
        description: 'Review user access permissions for financial systems',
        status: 'pending',
        type: 'analysis',
        progress: 0,
      },
    ],
    documentation: [
      {
        id: 'doc-page-5',
        title: 'SOX Controls',
        content: '# SOX Compliance Controls\n\n## IT General Controls\n- Change management\n- Access controls\n- Backup and recovery\n\n## Application Controls\n- Input validation\n- Processing controls\n- Output controls',
        order: 1,
        createdAt: '2025-09-18T09:00:00Z',
        updatedAt: '2025-09-18T09:00:00Z',
      },
    ],
    createdAt: '2025-09-18T08:00:00Z',
    updatedAt: '2025-09-18T10:00:00Z',
  },
];

